name: DevSecOps Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:        # permet de lancer le pipeline manuellement

permissions:
  contents: read
  security-events: write    # nécessaire pour envoyer les rapports dans l'onglet Security

jobs:
  secret-scan:
    name: Secret Scanning (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code (historique complet)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer Gitleaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.30.1/gitleaks_8.30.1_linux_x64.tar.gz
          tar -xzf gitleaks_8.30.1_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Scanner les secrets
        run: gitleaks dir . -v --report-format sarif --report-path gitleaks.sarif

      - name: Envoyer le rapport dans l'onglet Security
        if: always()
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      - name: Conserver le rapport comme artefact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-sarif-report
          path: gitleaks.sarif
